# Generated by Django 6.0.5 on 2026-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('valid', models.IntegerField()),
            ],
        ),
    ]
